twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        kernelProjectDir: '%kernel.project_dir%'
#        cartService: "%kernel.project_dir%/src/Service/CartSessionStorage"

when@test:
    twig:
        strict_variables: true
#        form_themes: ['bootstrap_5_layout.html.twig']
